### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by Eternity-Yarr** [ther10n73/jsonParser#10]
https://github.com/ther10n73/jsonParser/blob/master/adja-json-vdovin/src/main/java/ru/vdovin/jsonParser/JsonParseReader.java

переставь местами как положено методы/поля

**Comment by Eternity-Yarr** [comment]
и reader надо либо пометить `@NotNull` либо обработать возможный NPE из nextElement

**Comment by ther10n73** [comment]
done
