### ISSUE TITLE
Бессмысленный трайкетч

### ISSUE THREAD

**Issue by Eternity-Yarr** [ther10n73/jsonParser#11]
в ReflectionMapper 

```
       try {
            obj = createDefualtConstrucnor(jo, targetType);
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException(e);
        }
```

**Comment by Eternity-Yarr** [comment]
там же:

```
        try {
            Constructor<T> constructor = targetType.getDeclaredConstructor();
            obj = constructor.newInstance();
        } catch (Exception e) {
            throw new IllegalArgumentException(e.getMessage());
        }
```

теряется оригинальный эксепшн. Обязательно оставляй всегда и везде старый (ну не всегда но чаще всего надо)

**Comment by ther10n73** [comment]
done

**Comment by Eternity-Yarr** [comment]
не так делают :) делаешь коммит и пишешь Fixes #11 issue например, или похожее что-то

**Comment by Eternity-Yarr** [comment]
тогда можно будет посмотреть прям тут как ты чинил

**Comment by ther10n73** [comment]
аа... теперь понял как надо issue закрывать) только я все в один коммит зафигарил..

**Comment by Eternity-Yarr** [comment]
Ну это как раз плохо :) Каждое изменение должно быть как можно меньше(но полностью выполненым, считай чтоб приложение с любого комита можно было запускать) и идти отдельным коммитом.

**Comment by Eternity-Yarr** [comment]
INSIGNIFICANT_SIMBOLS  --> SYMBLOS
и Constructor  у тебя все еще везде createConstrucnor

**Comment by Eternity-Yarr** [comment]
Не спеши закрывать, если не уверен

**Comment by ther10n73** [comment]
Так я не закрывал, он автоматом закрылся...
